/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  DepositLibTest,
  DepositLibTestInterface,
} from "../../../../contracts/test/lib/DepositLibTest";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "recipientSaltHash",
            type: "bytes32",
          },
          {
            internalType: "uint32",
            name: "tokenIndex",
            type: "uint32",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct DepositLib.Deposit",
        name: "deposit",
        type: "tuple",
      },
    ],
    name: "getHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506103a0806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80638e522ff714610030575b600080fd5b61004a6004803603810190610045919061025e565b610060565b604051610057919061029a565b60405180910390f35b600061006b82610072565b9050919050565b60008160000151826020015183604001516040516020016100959392919061032d565b604051602081830303815290604052805190602001209050919050565b6000604051905090565b600080fd5b600080fd5b6000601f19601f8301169050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b61010f826100c6565b810181811067ffffffffffffffff8211171561012e5761012d6100d7565b5b80604052505050565b60006101416100b2565b905061014d8282610106565b919050565b6000819050919050565b61016581610152565b811461017057600080fd5b50565b6000813590506101828161015c565b92915050565b600063ffffffff82169050919050565b6101a181610188565b81146101ac57600080fd5b50565b6000813590506101be81610198565b92915050565b6000819050919050565b6101d7816101c4565b81146101e257600080fd5b50565b6000813590506101f4816101ce565b92915050565b6000606082840312156102105761020f6100c1565b5b61021a6060610137565b9050600061022a84828501610173565b600083015250602061023e848285016101af565b6020830152506040610252848285016101e5565b60408301525092915050565b600060608284031215610274576102736100bc565b5b6000610282848285016101fa565b91505092915050565b61029481610152565b82525050565b60006020820190506102af600083018461028b565b92915050565b6000819050919050565b6102d06102cb82610152565b6102b5565b82525050565b60008160e01b9050919050565b60006102ee826102d6565b9050919050565b61030661030182610188565b6102e3565b82525050565b6000819050919050565b610327610322826101c4565b61030c565b82525050565b600061033982866102bf565b60208201915061034982856102f5565b6004820191506103598284610316565b60208201915081905094935050505056fea26469706673582212201bde164858e1fb2526797e8ae87e72abeeb6159efcee675f5aca89ac7d9f6d6a64736f6c63430008180033";

type DepositLibTestConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DepositLibTestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DepositLibTest__factory extends ContractFactory {
  constructor(...args: DepositLibTestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DepositLibTest & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DepositLibTest__factory {
    return super.connect(runner) as DepositLibTest__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DepositLibTestInterface {
    return new Interface(_abi) as DepositLibTestInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DepositLibTest {
    return new Contract(address, _abi, runner) as unknown as DepositLibTest;
  }
}
